FROM multiarch/ubuntu-core:arm64-xenial

RUN apt update -y && apt install -y python3 python3-pip libatlas-base-dev gfortran python3-dev binutils cython

RUN pip3 install numpy scipy

RUN pip3 install pandas

RUN pip3 install scikit-learn

RUN apt install -y zlib1g-dev libjpeg-turbo8-dev libfreetype6 

RUN pip3 install pillow

RUN apt install -y libhdf5-10 libhdf5-serial-dev libhdf5-dev libhdf5-cpp-11

#RUN pip3 install h5py


