FROM multiarch/ubuntu-core:armhf-xenial

RUN apt update -y && apt install -y python3 python3-pip libatlas-base-dev gfortran python3-dev binutils

RUN pip3 install numpy scipy

RUN pip3 install pandas

RUN pip3 install scikit-learn

RUN pip3 install pillow

RUN pip3 install h5py


